#!/bin/sh

MAILBOX_NAME=$MBC_MAILBOX
MAILBOX_DIR=$MBC_DIRECTORY
NAMESPACE_PREFIX=$MBC_PREFIX
NAMESPACE_TYPE=$MBC_TYPE
NAMESPACE_INBOX=$MBC_INBOX
NAMESPACE_HIDDEN=$MBC_HIDDEN
NAMESPACE_SUBSCRIPTIONS=$MBC_SUBSCRIPTIONS
NAMESPACE_LIST=$MBC_LIST

